theme: jekyll-theme-primer
title: Automatic Playlist Generation
description: Automatic Playlist Generation
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
