theme: jekyll-theme-primer
title: Automatic Playlist
description: Automatic Playlist Recommender
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
